INTIMA_ANNOTATION_NAME = 'intima_test'
ARTERIES_ANNOTATION_NAME = "arteries/arterioles"
DEFAULT_ANNOTATIONS_REQ = [INTIMA_ANNOTATION_NAME, ARTERIES_ANNOTATION_NAME]
DEFAULT_DOCKER_TMP_PATH = '/mnt/girder_worker'
TMPDIR_ENV_NAME = 'TMPDIR'